# Generated by Django 2.2 on 2019-07-19 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190718_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
